/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lampa.alfabattle.first.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.lampa.alfabattle.first.entities.Atm;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * AtmResponse
 */
@JsonPropertyOrder({
        AtmResponse.JSON_PROPERTY_CITY,
        AtmResponse.JSON_PROPERTY_DEVICE_ID,
        AtmResponse.JSON_PROPERTY_LATITUDE,
        AtmResponse.JSON_PROPERTY_LOCATION,
        AtmResponse.JSON_PROPERTY_LONGITUDE,
        AtmResponse.JSON_PROPERTY_PAYMENTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-27T12:12:59.344522300+03:00[Europe/Moscow]")
public class AtmResponse {
    public static final String JSON_PROPERTY_CITY = "city";
    private String city;

    public static final String JSON_PROPERTY_DEVICE_ID = "deviceId";
    private Integer deviceId;

    public static final String JSON_PROPERTY_LATITUDE = "latitude";
    private String latitude;

    public static final String JSON_PROPERTY_LOCATION = "location";
    private String location;

    public static final String JSON_PROPERTY_LONGITUDE = "longitude";
    private String longitude;

    public static final String JSON_PROPERTY_PAYMENTS = "payments";
    private Boolean payments;

    public static AtmResponse valueOf(Atm atm) {
        AtmResponse atmResponse = new AtmResponse();
        atmResponse.setCity(atm.getCity());
        atmResponse.setLatitude(String.valueOf(atm.getLatitude()));
        atmResponse.setLongitude(String.valueOf(atm.getLongitude()));
        atmResponse.setLocation(String.valueOf(atm.getAddress()));
        atmResponse.setPayments(atm.getPayments());
        atmResponse.setDeviceId(atm.getExternal());

        return atmResponse;
    }


    public AtmResponse city(String city) {

        this.city = city;
        return this;
    }

    /**
     * Get city
     *
     * @return city
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_CITY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getCity() {
        return city;
    }


    public void setCity(String city) {
        this.city = city;
    }


    public AtmResponse deviceId(Integer deviceId) {

        this.deviceId = deviceId;
        return this;
    }

    /**
     * Get deviceId
     *
     * @return deviceId
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_DEVICE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getDeviceId() {
        return deviceId;
    }


    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }


    public AtmResponse latitude(String latitude) {

        this.latitude = latitude;
        return this;
    }

    /**
     * Get latitude
     *
     * @return latitude
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_LATITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLatitude() {
        return latitude;
    }


    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }


    public AtmResponse location(String location) {

        this.location = location;
        return this;
    }

    /**
     * Get location
     *
     * @return location
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLocation() {
        return location;
    }


    public void setLocation(String location) {
        this.location = location;
    }


    public AtmResponse longitude(String longitude) {

        this.longitude = longitude;
        return this;
    }

    /**
     * Get longitude
     *
     * @return longitude
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_LONGITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLongitude() {
        return longitude;
    }


    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }


    public AtmResponse payments(Boolean payments) {

        this.payments = payments;
        return this;
    }

    /**
     * Get payments
     *
     * @return payments
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_PAYMENTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getPayments() {
        return payments;
    }


    public void setPayments(Boolean payments) {
        this.payments = payments;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AtmResponse atmResponse = (AtmResponse) o;
        return Objects.equals(this.city, atmResponse.city) &&
                Objects.equals(this.deviceId, atmResponse.deviceId) &&
                Objects.equals(this.latitude, atmResponse.latitude) &&
                Objects.equals(this.location, atmResponse.location) &&
                Objects.equals(this.longitude, atmResponse.longitude) &&
                Objects.equals(this.payments, atmResponse.payments);
    }

    @Override
    public int hashCode() {
        return Objects.hash(city, deviceId, latitude, location, longitude, payments);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AtmResponse {\n");
        sb.append("    city: ").append(toIndentedString(city)).append("\n");
        sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
        sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
        sb.append("    location: ").append(toIndentedString(location)).append("\n");
        sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
        sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

