/*
 * Сервис проверки статуса банкоматов
 * Сервис, возвращающий информацию о банкоматах Альфа-Банка
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@alfabank.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lampa.alfabattle.first.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ATMServices
 */
@JsonPropertyOrder({
        ATMServices.JSON_PROPERTY_CARD_CASH_IN,
        ATMServices.JSON_PROPERTY_CARD_CASH_OUT,
        ATMServices.JSON_PROPERTY_CARD_PAYMENTS,
        ATMServices.JSON_PROPERTY_CASH_IN,
        ATMServices.JSON_PROPERTY_CASH_OUT,
        ATMServices.JSON_PROPERTY_PAYMENTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-27T10:26:33.214272+03:00[Europe/Moscow]")
public class ATMServices {
    public static final String JSON_PROPERTY_CARD_CASH_IN = "cardCashIn";
    private String cardCashIn;

    public static final String JSON_PROPERTY_CARD_CASH_OUT = "cardCashOut";
    private String cardCashOut;

    public static final String JSON_PROPERTY_CARD_PAYMENTS = "cardPayments";
    private String cardPayments;

    public static final String JSON_PROPERTY_CASH_IN = "cashIn";
    private String cashIn;

    public static final String JSON_PROPERTY_CASH_OUT = "cashOut";
    private String cashOut;

    public static final String JSON_PROPERTY_PAYMENTS = "payments";
    private String payments;


    public ATMServices cardCashIn(String cardCashIn) {

        this.cardCashIn = cardCashIn;
        return this;
    }

    /**
     * Операции внесения наличных денежных средств с использованием платежных карт и их реквизитов
     *
     * @return cardCashIn
     **/

    @ApiModelProperty(value = "Операции внесения наличных денежных средств с использованием платежных карт и их реквизитов")
    @JsonProperty(JSON_PROPERTY_CARD_CASH_IN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getCardCashIn() {
        return cardCashIn;
    }


    public void setCardCashIn(String cardCashIn) {
        this.cardCashIn = cardCashIn;
    }


    public ATMServices cardCashOut(String cardCashOut) {

        this.cardCashOut = cardCashOut;
        return this;
    }

    /**
     * Операция выдачи наличных с использованием платежных карт и их реквизитов
     *
     * @return cardCashOut
     **/

    @ApiModelProperty(value = "Операция выдачи наличных с использованием платежных карт и их реквизитов")
    @JsonProperty(JSON_PROPERTY_CARD_CASH_OUT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getCardCashOut() {
        return cardCashOut;
    }


    public void setCardCashOut(String cardCashOut) {
        this.cardCashOut = cardCashOut;
    }


    public ATMServices cardPayments(String cardPayments) {

        this.cardPayments = cardPayments;
        return this;
    }

    /**
     * Платежи (оплата товаров и услуг) в пользу поставщиков услуг и третьих лиц с использованием платежных карт и их реквизитов
     *
     * @return cardPayments
     **/

    @ApiModelProperty(value = "Платежи (оплата товаров и услуг) в пользу поставщиков услуг и третьих лиц с использованием платежных карт и их реквизитов")
    @JsonProperty(JSON_PROPERTY_CARD_PAYMENTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getCardPayments() {
        return cardPayments;
    }


    public void setCardPayments(String cardPayments) {
        this.cardPayments = cardPayments;
    }


    public ATMServices cashIn(String cashIn) {

        this.cashIn = cashIn;
        return this;
    }

    /**
     * Операции внесения наличных денежных средств БЕЗ использования платежных карт и их реквизитов
     *
     * @return cashIn
     **/

    @ApiModelProperty(value = "Операции внесения наличных денежных средств БЕЗ использования платежных карт и их реквизитов")
    @JsonProperty(JSON_PROPERTY_CASH_IN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getCashIn() {
        return cashIn;
    }


    public void setCashIn(String cashIn) {
        this.cashIn = cashIn;
    }


    public ATMServices cashOut(String cashOut) {

        this.cashOut = cashOut;
        return this;
    }

    /**
     * Операция выдачи наличных БЕЗ использования платежных карт и их реквизитов
     *
     * @return cashOut
     **/

    @ApiModelProperty(value = "Операция выдачи наличных БЕЗ использования платежных карт и их реквизитов")
    @JsonProperty(JSON_PROPERTY_CASH_OUT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getCashOut() {
        return cashOut;
    }


    public void setCashOut(String cashOut) {
        this.cashOut = cashOut;
    }


    public ATMServices payments(String payments) {

        this.payments = payments;
        return this;
    }

    /**
     * Платежи (Оплата товаров и услуг) в пользу поставщиков услуг и третьих лиц БЕЗ использования платежных карт и их реквизитов
     *
     * @return payments
     **/

    @ApiModelProperty(value = "Платежи (Оплата товаров и услуг) в пользу поставщиков услуг и третьих лиц БЕЗ использования платежных карт и их реквизитов")
    @JsonProperty(JSON_PROPERTY_PAYMENTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPayments() {
        return payments;
    }


    public void setPayments(String payments) {
        this.payments = payments;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ATMServices atMServices = (ATMServices) o;
        return Objects.equals(this.cardCashIn, atMServices.cardCashIn) &&
                Objects.equals(this.cardCashOut, atMServices.cardCashOut) &&
                Objects.equals(this.cardPayments, atMServices.cardPayments) &&
                Objects.equals(this.cashIn, atMServices.cashIn) &&
                Objects.equals(this.cashOut, atMServices.cashOut) &&
                Objects.equals(this.payments, atMServices.payments);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cardCashIn, cardCashOut, cardPayments, cashIn, cashOut, payments);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ATMServices {\n");
        sb.append("    cardCashIn: ").append(toIndentedString(cardCashIn)).append("\n");
        sb.append("    cardCashOut: ").append(toIndentedString(cardCashOut)).append("\n");
        sb.append("    cardPayments: ").append(toIndentedString(cardPayments)).append("\n");
        sb.append("    cashIn: ").append(toIndentedString(cashIn)).append("\n");
        sb.append("    cashOut: ").append(toIndentedString(cashOut)).append("\n");
        sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

